joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  

forklift_controller:
  type: effort_controllers/JointPositionController
  joint: fork_moving_base_joint
  pid: {p: 70.0, i: 1.0, d: 10.0}
