pioneer1:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  #  left_wheel_position_controller:
  #  type: effort_controllers/JointPositionController
  #  joint: base_left_wheel_joint
  #  pid: {p: 100.0, i: 0.01, d: 10.0}
  #right_wheel_position_controller:
  #  type: effort_controllers/JointPositionController
  #  joint: base_right_wheel_joint
  #  pid: {p: 100.0, i: 0.01, d: 10.0}
#  twister_position_controller:
#    type: effort_controllers/JointPositionController
#    joint: twister_joint
#    pid: {p: 100.0, i: 0.01, d: 10.0}
#  differential_drive_controller:
#    type: diff_drive_controller/DiffDriveController
#    left_wheel: wheel_left_joint
#    right_wheel: wheel_right_joint
#    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
#    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

  fork_lift_controller:
    type: effort_controllers/JointPositionController
    joint: fork_moving_base_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

pioneer2:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  fork_lift_controller:
    type: effort_controllers/JointPositionController
    joint: fork_moving_base_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

