joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  

fork_lift_controller:
  type: effort_controllers/JointPositionController
  joint: fork_moving_base_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}
